export const CREATE_ITEM_REQUEST = 'CREATE_ITEM_REQUEST';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

//Membership Page
export const CREATE_MEMBER_REQUEST = 'CREATE_MEMBER_REQUEST';
export const CREATE_MEMBER_SUCCESS = 'CREATE_MEMBER_SUCCESS';
export const CREATE_MEMBER_FAILURE = 'CREATE_MEMBER_FAILURE';

export const FETCH_MEMBERS_REQUEST = 'FETCH_MEMBERS_REQUEST';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_FAILURE = 'FETCH_MEMBERS_FAILURE';

export const UPDATE_MEMBER_REQUEST = 'UPDATE_MEMBER_REQUEST';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';
export const UPDATE_MEMBER_FAILURE = 'UPDATE_MEMBER_FAILURE';

export const DELETE_MEMBER_REQUEST = 'DELETE_MEMBER_REQUEST';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_FAILURE = 'DELETE_MEMBER_FAILURE';

//Membership Page
export const CREATE_CASHIER_REQUEST = 'CREATE_CASHIER_REQUEST';
export const CREATE_CASHIER_SUCCESS = 'CREATE_CASHIER_SUCCESS';
export const CREATE_CASHIER_FAILURE = 'CREATE_CASHIER_FAILURE';

export const FETCH_CASHIERS_REQUEST = 'FETCH_CASHIERS_REQUEST';
export const FETCH_CASHIERS_SUCCESS = 'FETCH_CASHIERS_SUCCESS';
export const FETCH_CASHIERS_FAILURE = 'FETCH_CASHIERS_FAILURE';

export const UPDATE_CASHIER_REQUEST = 'UPDATE_CASHIER_REQUEST';
export const UPDATE_CASHIER_SUCCESS = 'UPDATE_CASHIER_SUCCESS';
export const UPDATE_CASHIER_FAILURE = 'UPDATE_CASHIER_FAILURE';

export const DELETE_CASHIER_REQUEST = 'DELETE_CASHIER_REQUEST';
export const DELETE_CASHIER_SUCCESS = 'DELETE_CASHIER_SUCCESS';
export const DELETE_CASHIER_FAILURE = 'DELETE_CASHIER_FAILURE';

//Order Page
export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_ORDERSBYID_REQUEST = 'FETCH_ORDERSBYID_REQUEST';
export const FETCH_ORDERSBYID_SUCCESS = 'FETCH_ORDERSBYID_SUCCESS';
export const FETCH_ORDERSBYID_FAILURE = 'FETCH_ORDERSBYID_FAILURE';

export const FETCH_ORDERSALL_REQUEST = 'FETCH_ORDERSALL_REQUEST';
export const FETCH_ORDERSALL_SUCCESS = 'FETCH_ORDERSALL_SUCCESS';
export const FETCH_ORDERSALL_FAILURE = 'FETCH_ORDERSALL_FAILURE';

export const FETCH_ORDERSSEARCH_REQUEST = 'FETCH_ORDERSSEARCH_REQUEST';
export const FETCH_ORDERSSEARCH_SUCCESS = 'FETCH_ORDERSSEARCH_SUCCESS';
export const FETCH_ORDERSSEARCH_FAILURE = 'FETCH_ORDERSSEARCH_FAILURE';